[[dependencies.catocraftmod]]
modId="spell_engine"
mandatory=true
versionRange="[1.8.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.catocraftmod]]
modId="spell_power"
mandatory=true
versionRange="[1.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.catocraftmod]]
modId="playeranimator"
mandatory=true
versionRange="[2.0.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.catocraftmod]]
modId="cloth-config"
mandatory=true
versionRange="[15.0.140,)"
ordering="NONE"
side="CLIENT"

[[dependencies.catocraftmod]]
modId="fabric_api"
mandatory=true
versionRange="[0.115.6+2.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.catocraftmod]]
modId="owo-lib"
mandatory=true
versionRange="[0.12.15.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.catocraftmod]]
modId="accessories"
mandatory=true
versionRange="[1.1.0-beta.52,)"
ordering="NONE"
side="BOTH"